package guardduty

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsguardduty"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/guardduty/internal"
)

// Represents a GuardDuty detector.
//
// A detector is an object that represents the GuardDuty service. A detector is
// required for GuardDuty to become operational.
// See: [AWS::GuardDuty::Detector](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html)
//
type Detector interface {
	awscdk.Resource
	IDetector
	// The Amazon Resource Name (ARN) of the GuardDuty detector.
	DetectorArn() *string
	// The ID generated by AWS for the GuardDuty detector.
	DetectorId() *string
	// Specifies whether the detector is to be enabled on creation.
	// See: [Detector Enable](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html#cfn-guardduty-detector-enable)
	//
	Enabled() *bool
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// Collection of additional features to be configured on the detector.
	// See: [Detector Features](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html#cfn-guardduty-detector-features)
	//
	Features() *[]IFeature
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// Specifies how frequently updated findings are exported.
	// See: [Detector FindingPublishingFrequency](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html#cfn-guardduty-detector-findingpublishingfrequency)
	//
	PublishingFrequency() FindingPublishingFrequency
	// The underlying Detector CloudFormation resource.
	// See: [AWS::GuardDuty::Detector](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html)
	//
	Resource() awsguardduty.CfnDetector
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Configures a feature to be enabled on the detector.
	//
	// Returns: The detector on which the feature was configured.
	AddFeature(feature IFeature) Detector
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Detector
type jsiiProxy_Detector struct {
	internal.Type__awscdkResource
	jsiiProxy_IDetector
}

func (j *jsiiProxy_Detector) DetectorArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"detectorArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) DetectorId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"detectorId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) Enabled() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) Features() *[]IFeature {
	var returns *[]IFeature
	_jsii_.Get(
		j,
		"features",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) PublishingFrequency() FindingPublishingFrequency {
	var returns FindingPublishingFrequency
	_jsii_.Get(
		j,
		"publishingFrequency",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) Resource() awsguardduty.CfnDetector {
	var returns awsguardduty.CfnDetector
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Detector) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Creates a new instance of the Detector resource.
func NewDetector(scope constructs.IConstruct, id *string, props *DetectorProps) Detector {
	_init_.Initialize()

	if err := validateNewDetectorParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Detector{}

	_jsii_.Create(
		"cdk-extensions.guardduty.Detector",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the Detector resource.
func NewDetector_Override(d Detector, scope constructs.IConstruct, id *string, props *DetectorProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.guardduty.Detector",
		[]interface{}{scope, id, props},
		d,
	)
}

// Imports an existing GuardDuty detector by specifying its Amazon Resource Name (ARN).
//
// Returns: An object representing the imported GuardDuty detector.
func Detector_FromDetectorArn(scope constructs.IConstruct, id *string, detectorArn *string) IDetector {
	_init_.Initialize()

	if err := validateDetector_FromDetectorArnParameters(scope, id, detectorArn); err != nil {
		panic(err)
	}
	var returns IDetector

	_jsii_.StaticInvoke(
		"cdk-extensions.guardduty.Detector",
		"fromDetectorArn",
		[]interface{}{scope, id, detectorArn},
		&returns,
	)

	return returns
}

// Imports an existing GuardDuty detector by explicitly specifying its attributes.
//
// Returns: An object representing the imported GuardDuty detector.
func Detector_FromDetectorAttributes(scope constructs.IConstruct, id *string, attrs *DetectorAttributes) IDetector {
	_init_.Initialize()

	if err := validateDetector_FromDetectorAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IDetector

	_jsii_.StaticInvoke(
		"cdk-extensions.guardduty.Detector",
		"fromDetectorAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Imports an existing GuardDuty detector by specifiying its AWS generated ID.
//
// Returns: An object representing the imported GuardDuty detector.
func Detector_FromDetectorId(scope constructs.IConstruct, id *string, detectorId *string) IDetector {
	_init_.Initialize()

	if err := validateDetector_FromDetectorIdParameters(scope, id, detectorId); err != nil {
		panic(err)
	}
	var returns IDetector

	_jsii_.StaticInvoke(
		"cdk-extensions.guardduty.Detector",
		"fromDetectorId",
		[]interface{}{scope, id, detectorId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func Detector_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateDetector_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.guardduty.Detector",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func Detector_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateDetector_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.guardduty.Detector",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func Detector_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateDetector_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.guardduty.Detector",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func Detector_ARN_FORMAT() awscdk.ArnFormat {
	_init_.Initialize()
	var returns awscdk.ArnFormat
	_jsii_.StaticGet(
		"cdk-extensions.guardduty.Detector",
		"ARN_FORMAT",
		&returns,
	)
	return returns
}

func (d *jsiiProxy_Detector) AddFeature(feature IFeature) Detector {
	if err := d.validateAddFeatureParameters(feature); err != nil {
		panic(err)
	}
	var returns Detector

	_jsii_.Invoke(
		d,
		"addFeature",
		[]interface{}{feature},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Detector) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := d.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (d *jsiiProxy_Detector) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Detector) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := d.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		d,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Detector) GetResourceNameAttribute(nameAttr *string) *string {
	if err := d.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		d,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Detector) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

