package guardduty


// Configuration for importing an existing GuardDuty detector.
type DetectorAttributes struct {
	// The Amazon Resource Name (ARN) of the GuardDuty detector.
	DetectorArn *string `field:"optional" json:"detectorArn" yaml:"detectorArn"`
	// The ID generated by AWS for the GuardDuty detector.
	DetectorId *string `field:"optional" json:"detectorId" yaml:"detectorId"`
}

