package k8saws

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awseks"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsssm"
	"github.com/aws/constructs-go/constructs/v10"
)

// A secret store that allows parameters from Systems Manager to be synchronized into Kubernetes as Kubernetes secrets.
type SsmParameterSecretStore interface {
	AwsSecretStore
	// The EKS cluster where the secret store should be created.
	Cluster() awseks.ICluster
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The Kubernetes manifest that defines the secret store.
	Manifest() awseks.KubernetesManifest
	// A human friendly name for the secret store.
	Name() *string
	// The Kubernetes namespace where the secret store should be created.
	Namespace() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The name of the secret store as it appears in Kubernetes.
	SecretStoreName() *string
	// The name of the service provider backing the secret store.
	Service() *string
	// A Kubernetes service account mapped to an IAM role that provides the necessary permissions to sychronize secrets from an AWS rpvoder.
	ServiceAccount() awseks.ServiceAccount
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Registers a new SSSM parameter to be synchronized into Kubernetes.
	//
	// Returns: The external secret configuration that was added.
	AddSecret(id *string, parameter awsssm.IParameter, options *ExternalSecretOptions) ExternalSecret
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for SsmParameterSecretStore
type jsiiProxy_SsmParameterSecretStore struct {
	jsiiProxy_AwsSecretStore
}

func (j *jsiiProxy_SsmParameterSecretStore) Cluster() awseks.ICluster {
	var returns awseks.ICluster
	_jsii_.Get(
		j,
		"cluster",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Manifest() awseks.KubernetesManifest {
	var returns awseks.KubernetesManifest
	_jsii_.Get(
		j,
		"manifest",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Namespace() *string {
	var returns *string
	_jsii_.Get(
		j,
		"namespace",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) SecretStoreName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"secretStoreName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Service() *string {
	var returns *string
	_jsii_.Get(
		j,
		"service",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) ServiceAccount() awseks.ServiceAccount {
	var returns awseks.ServiceAccount
	_jsii_.Get(
		j,
		"serviceAccount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_SsmParameterSecretStore) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Creates a new instance of the SsmParameterSecretStore class.
func NewSsmParameterSecretStore(scope constructs.Construct, id *string, props *SsmParameterSecretStoreProps) SsmParameterSecretStore {
	_init_.Initialize()

	if err := validateNewSsmParameterSecretStoreParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_SsmParameterSecretStore{}

	_jsii_.Create(
		"cdk-extensions.k8s_aws.SsmParameterSecretStore",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the SsmParameterSecretStore class.
func NewSsmParameterSecretStore_Override(s SsmParameterSecretStore, scope constructs.Construct, id *string, props *SsmParameterSecretStoreProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.k8s_aws.SsmParameterSecretStore",
		[]interface{}{scope, id, props},
		s,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func SsmParameterSecretStore_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateSsmParameterSecretStore_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.k8s_aws.SsmParameterSecretStore",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func SsmParameterSecretStore_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateSsmParameterSecretStore_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.k8s_aws.SsmParameterSecretStore",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func SsmParameterSecretStore_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateSsmParameterSecretStore_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.k8s_aws.SsmParameterSecretStore",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func SsmParameterSecretStore_NAME_VALIDATOR_REGEX() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.k8s_aws.SsmParameterSecretStore",
		"NAME_VALIDATOR_REGEX",
		&returns,
	)
	return returns
}

func (s *jsiiProxy_SsmParameterSecretStore) AddSecret(id *string, parameter awsssm.IParameter, options *ExternalSecretOptions) ExternalSecret {
	if err := s.validateAddSecretParameters(id, parameter, options); err != nil {
		panic(err)
	}
	var returns ExternalSecret

	_jsii_.Invoke(
		s,
		"addSecret",
		[]interface{}{id, parameter, options},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_SsmParameterSecretStore) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := s.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (s *jsiiProxy_SsmParameterSecretStore) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		s,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_SsmParameterSecretStore) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := s.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		s,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_SsmParameterSecretStore) GetResourceNameAttribute(nameAttr *string) *string {
	if err := s.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		s,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_SsmParameterSecretStore) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		s,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

