package ec2


// Configuration for importing an existing IPAM scope.
type IpamScopeAttributes struct {
	// The IPAM to which the scope belongs.
	Ipam IIpam `field:"optional" json:"ipam" yaml:"ipam"`
	// The Amazon Resource Name (ARN) of the IPAM scope.
	IpamScopeArn *string `field:"optional" json:"ipamScopeArn" yaml:"ipamScopeArn"`
	// The ID generated by AWS for the IPAM scope.
	IpamScopeId *string `field:"optional" json:"ipamScopeId" yaml:"ipamScopeId"`
	// Defines if the scope is the default scope or not.
	IsDefault *bool `field:"optional" json:"isDefault" yaml:"isDefault"`
	// The number of pools in a scope.
	PoolCount *float64 `field:"optional" json:"poolCount" yaml:"poolCount"`
	// The type of the scope.
	ScopeType *string `field:"optional" json:"scopeType" yaml:"scopeType"`
}

