package ec2

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2/internal"
)

type IpamPool interface {
	awscdk.Resource
	IIpamPool
	AddressConfiguration() AddressConfiguration
	AutoImport() *bool
	Description() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	IpamPoolArn() *string
	IpamPoolDepth() *float64
	IpamPoolId() *string
	IpamPoolIpamArn() *string
	IpamPoolScopeArn() *string
	IpamPoolScopeType() *string
	IpamPoolState() *string
	IpamPoolStateMessage() *string
	IpamScope() IIpamScope
	IpFamily() IpFamily
	Locale() *string
	Name() *string
	// The tree node.
	Node() constructs.Node
	ParentPool() IIpamPool
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	PublicIpSource() PublicIpSource
	Resource() awsec2.CfnIPAMPool
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	AddChildPool(id *string, options *AddChildPoolOptions) IIpamPool
	AddCidrToPool(id *string, options *AddCidrToPoolOptions) *AddCidrToPoolResult
	AddTagRestriction(key *string, value *string) IIpamPool
	AllocateCidrFromPool(id *string, options *AllocateCidrFromPoolOptions) IIpamAllocation
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
	ValidateChildLocale(locale *string) *bool
	ValidateNestingSupport() *bool
}

// The jsii proxy struct for IpamPool
type jsiiProxy_IpamPool struct {
	internal.Type__awscdkResource
	jsiiProxy_IIpamPool
}

func (j *jsiiProxy_IpamPool) AddressConfiguration() AddressConfiguration {
	var returns AddressConfiguration
	_jsii_.Get(
		j,
		"addressConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) AutoImport() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"autoImport",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolDepth() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"ipamPoolDepth",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolIpamArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolIpamArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolScopeArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolScopeArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolScopeType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolScopeType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolState() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolState",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamPoolStateMessage() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamPoolStateMessage",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpamScope() IIpamScope {
	var returns IIpamScope
	_jsii_.Get(
		j,
		"ipamScope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) IpFamily() IpFamily {
	var returns IpFamily
	_jsii_.Get(
		j,
		"ipFamily",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Locale() *string {
	var returns *string
	_jsii_.Get(
		j,
		"locale",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) ParentPool() IIpamPool {
	var returns IIpamPool
	_jsii_.Get(
		j,
		"parentPool",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) PublicIpSource() PublicIpSource {
	var returns PublicIpSource
	_jsii_.Get(
		j,
		"publicIpSource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Resource() awsec2.CfnIPAMPool {
	var returns awsec2.CfnIPAMPool
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamPool) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewIpamPool(scope constructs.IConstruct, id *string, props *IpamPoolProps) IpamPool {
	_init_.Initialize()

	if err := validateNewIpamPoolParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_IpamPool{}

	_jsii_.Create(
		"cdk-extensions.ec2.IpamPool",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewIpamPool_Override(i IpamPool, scope constructs.IConstruct, id *string, props *IpamPoolProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2.IpamPool",
		[]interface{}{scope, id, props},
		i,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func IpamPool_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateIpamPool_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamPool",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func IpamPool_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpamPool_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamPool",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func IpamPool_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpamPool_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamPool",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) AddChildPool(id *string, options *AddChildPoolOptions) IIpamPool {
	if err := i.validateAddChildPoolParameters(id, options); err != nil {
		panic(err)
	}
	var returns IIpamPool

	_jsii_.Invoke(
		i,
		"addChildPool",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) AddCidrToPool(id *string, options *AddCidrToPoolOptions) *AddCidrToPoolResult {
	if err := i.validateAddCidrToPoolParameters(id, options); err != nil {
		panic(err)
	}
	var returns *AddCidrToPoolResult

	_jsii_.Invoke(
		i,
		"addCidrToPool",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) AddTagRestriction(key *string, value *string) IIpamPool {
	if err := i.validateAddTagRestrictionParameters(key, value); err != nil {
		panic(err)
	}
	var returns IIpamPool

	_jsii_.Invoke(
		i,
		"addTagRestriction",
		[]interface{}{key, value},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) AllocateCidrFromPool(id *string, options *AllocateCidrFromPoolOptions) IIpamAllocation {
	if err := i.validateAllocateCidrFromPoolParameters(id, options); err != nil {
		panic(err)
	}
	var returns IIpamAllocation

	_jsii_.Invoke(
		i,
		"allocateCidrFromPool",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_IpamPool) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) ValidateChildLocale(locale *string) *bool {
	var returns *bool

	_jsii_.Invoke(
		i,
		"validateChildLocale",
		[]interface{}{locale},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamPool) ValidateNestingSupport() *bool {
	var returns *bool

	_jsii_.Invoke(
		i,
		"validateNestingSupport",
		nil, // no parameters
		&returns,
	)

	return returns
}

