package ec2

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2/internal"
)

// Represents an IPAM scope.
//
// In IPAM, a scope is the highest-level container within IPAM. An IPAM
// contains two default scopes. Each scope represents the IP space for a single
// network. The private scope is intended for all private IP address space. The
// public scope is intended for all public IP address space. Scopes enable you
// to reuse IP addresses across multiple unconnected networks without causing
// IP address overlap or conflict.
// See: [AWS::EC2::IPAMScope](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html)
//
type IpamScope interface {
	awscdk.Resource
	IIpamScope
	// The description of the scope.
	// See: [IPAMScope Description](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-description)
	//
	Description() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The IPAM for which you're creating this scope.
	// See: [IPAMScope IpamId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-ipamid)
	//
	Ipam() IIpam
	// The ARN of the scope.
	IpamScopeArn() *string
	// The ID of an IPAM scope.
	IpamScopeId() *string
	// The ARN of an IPAM.
	IpamScopeIpamArn() *string
	// Defines if the scope is the default scope or not.
	IpamScopeIsDefault() awscdk.IResolvable
	// The number of pools in a scope.
	IpamScopePoolCount() *float64
	// The type of the scope.
	IpamScopeType() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The underlying IPAM scope CloudFormation resource.
	// See: [AWS::EC2::IPAMScope](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html)
	//
	Resource() awsec2.CfnIPAMScope
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Adds an IPAM pool to the IPAM scope.
	//
	// A pool is a collection of contiguous IP address ranges (or CIDRs). IPAM
	// pools enable you to organize your IP addresses according to your routing
	// and security needs.
	//
	// Returns: The pool that was added to the scope.
	// See: [How IPAM works](https://docs.aws.amazon.com/vpc/latest/ipam/how-it-works-ipam.html)
	//
	AddPool(id *string, options *IpamPoolOptions) IIpamPool
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for IpamScope
type jsiiProxy_IpamScope struct {
	internal.Type__awscdkResource
	jsiiProxy_IIpamScope
}

func (j *jsiiProxy_IpamScope) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) Ipam() IIpam {
	var returns IIpam
	_jsii_.Get(
		j,
		"ipam",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) IpamScopeArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) IpamScopeId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) IpamScopeIpamArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeIpamArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) IpamScopeIsDefault() awscdk.IResolvable {
	var returns awscdk.IResolvable
	_jsii_.Get(
		j,
		"ipamScopeIsDefault",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) IpamScopePoolCount() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"ipamScopePoolCount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) IpamScopeType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) Resource() awsec2.CfnIPAMScope {
	var returns awsec2.CfnIPAMScope
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamScope) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Creates a new instance of the IpamScope class.
func NewIpamScope(scope constructs.IConstruct, id *string, props *IpamScopeProps) IpamScope {
	_init_.Initialize()

	if err := validateNewIpamScopeParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_IpamScope{}

	_jsii_.Create(
		"cdk-extensions.ec2.IpamScope",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the IpamScope class.
func NewIpamScope_Override(i IpamScope, scope constructs.IConstruct, id *string, props *IpamScopeProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2.IpamScope",
		[]interface{}{scope, id, props},
		i,
	)
}

// Imports an existing IPAM scope by specifying its Amazon Resource Name (ARN).
//
// Returns: An object representing the imported IPAM scope.
func IpamScope_FromIpamScopeArn(scope constructs.IConstruct, id *string, ipamScopeArn *string) IIpamScope {
	_init_.Initialize()

	if err := validateIpamScope_FromIpamScopeArnParameters(scope, id, ipamScopeArn); err != nil {
		panic(err)
	}
	var returns IIpamScope

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamScope",
		"fromIpamScopeArn",
		[]interface{}{scope, id, ipamScopeArn},
		&returns,
	)

	return returns
}

// Imports an existing IAPM scope by explicitly specifying its attributes.
//
// Returns: An object representing the imported IPAM scope.
func IpamScope_FromIpamScopeAttributes(scope constructs.IConstruct, id *string, attrs *IpamScopeAttributes) IIpamScope {
	_init_.Initialize()

	if err := validateIpamScope_FromIpamScopeAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IIpamScope

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamScope",
		"fromIpamScopeAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Imports an existing IPAM scope by explicitly specifying its AWS generated ID.
//
// Returns: An object representing the imported IPAM scope.
func IpamScope_FromIpamScopeId(scope constructs.IConstruct, id *string, ipamScopeId *string) IIpamScope {
	_init_.Initialize()

	if err := validateIpamScope_FromIpamScopeIdParameters(scope, id, ipamScopeId); err != nil {
		panic(err)
	}
	var returns IIpamScope

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamScope",
		"fromIpamScopeId",
		[]interface{}{scope, id, ipamScopeId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func IpamScope_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateIpamScope_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamScope",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func IpamScope_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpamScope_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamScope",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func IpamScope_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpamScope_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamScope",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func IpamScope_ARN_FORMAT() awscdk.ArnFormat {
	_init_.Initialize()
	var returns awscdk.ArnFormat
	_jsii_.StaticGet(
		"cdk-extensions.ec2.IpamScope",
		"ARN_FORMAT",
		&returns,
	)
	return returns
}

func (i *jsiiProxy_IpamScope) AddPool(id *string, options *IpamPoolOptions) IIpamPool {
	if err := i.validateAddPoolParameters(id, options); err != nil {
		panic(err)
	}
	var returns IIpamPool

	_jsii_.Invoke(
		i,
		"addPool",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamScope) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_IpamScope) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamScope) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamScope) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamScope) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

