package ec2

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2/internal"
)

type IpamResourceDiscoveryAssociation interface {
	awscdk.Resource
	IIpamResourceDiscoveryAssociation
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	Ipam() IIpam
	IpamResourceDiscovery() IIpamResourceDiscovery
	IpamResourceDiscoveryAssociationArn() *string
	IpamResourceDiscoveryAssociationId() *string
	IpamResourceDiscoveryAssociationIpamArn() *string
	IpamResourceDiscoveryAssociationIpamRegion() *string
	IpamResourceDiscoveryAssociationIsDefault() awscdk.IResolvable
	IpamResourceDiscoveryAssociationOwnerId() *string
	IpamResourceDiscoveryAssociationResourceDiscoveryId() *string
	IpamResourceDiscoveryAssociationResourceDiscoveryStatus() *string
	IpamResourceDiscoveryAssociationState() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	Resource() awsec2.CfnIPAMResourceDiscoveryAssociation
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for IpamResourceDiscoveryAssociation
type jsiiProxy_IpamResourceDiscoveryAssociation struct {
	internal.Type__awscdkResource
	jsiiProxy_IIpamResourceDiscoveryAssociation
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) Ipam() IIpam {
	var returns IIpam
	_jsii_.Get(
		j,
		"ipam",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscovery() IIpamResourceDiscovery {
	var returns IIpamResourceDiscovery
	_jsii_.Get(
		j,
		"ipamResourceDiscovery",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationIpamArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationIpamArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationIpamRegion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationIpamRegion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationIsDefault() awscdk.IResolvable {
	var returns awscdk.IResolvable
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationIsDefault",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationOwnerId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationOwnerId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationResourceDiscoveryId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationResourceDiscoveryId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationResourceDiscoveryStatus() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationResourceDiscoveryStatus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) IpamResourceDiscoveryAssociationState() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamResourceDiscoveryAssociationState",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) Resource() awsec2.CfnIPAMResourceDiscoveryAssociation {
	var returns awsec2.CfnIPAMResourceDiscoveryAssociation
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpamResourceDiscoveryAssociation) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewIpamResourceDiscoveryAssociation(scope constructs.IConstruct, id *string, props *IpamResourceDiscoveryAssociationProps) IpamResourceDiscoveryAssociation {
	_init_.Initialize()

	if err := validateNewIpamResourceDiscoveryAssociationParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_IpamResourceDiscoveryAssociation{}

	_jsii_.Create(
		"cdk-extensions.ec2.IpamResourceDiscoveryAssociation",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewIpamResourceDiscoveryAssociation_Override(i IpamResourceDiscoveryAssociation, scope constructs.IConstruct, id *string, props *IpamResourceDiscoveryAssociationProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2.IpamResourceDiscoveryAssociation",
		[]interface{}{scope, id, props},
		i,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func IpamResourceDiscoveryAssociation_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateIpamResourceDiscoveryAssociation_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamResourceDiscoveryAssociation",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func IpamResourceDiscoveryAssociation_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpamResourceDiscoveryAssociation_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamResourceDiscoveryAssociation",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func IpamResourceDiscoveryAssociation_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpamResourceDiscoveryAssociation_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.IpamResourceDiscoveryAssociation",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamResourceDiscoveryAssociation) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_IpamResourceDiscoveryAssociation) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamResourceDiscoveryAssociation) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamResourceDiscoveryAssociation) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpamResourceDiscoveryAssociation) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

