package ec2


// Configuration for importing an existing IPAM.
type IpamAttributes struct {
	// The Amazon Resource Name (ARN) of the IPAM.
	IpamArn *string `field:"optional" json:"ipamArn" yaml:"ipamArn"`
	// The ID generated by AWS for the IPAM.
	IpamId *string `field:"optional" json:"ipamId" yaml:"ipamId"`
	// The IPAM's default private scope.
	PrivateDefaultScope IPrivateIpamScope `field:"optional" json:"privateDefaultScope" yaml:"privateDefaultScope"`
	// The IPAM's default public scope.
	PublicDefaultScope IPublicIpamScope `field:"optional" json:"publicDefaultScope" yaml:"publicDefaultScope"`
	// The number of scopes in the IPAM.
	ScopeCount *float64 `field:"optional" json:"scopeCount" yaml:"scopeCount"`
}

