package ec2

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2/internal"
)

type PrivateIpamScope interface {
	awscdk.Resource
	IPrivateIpamScope
	// The description of the scope.
	// See: [IPAMScope Description](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-description)
	//
	Description() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The IPAM for which you're creating this scope.
	// See: [IPAMScope IpamId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-ipamid)
	//
	Ipam() IIpam
	// The ARN of the scope.
	IpamScopeArn() *string
	// The ID of an IPAM scope.
	IpamScopeId() *string
	// The ARN of an IPAM.
	IpamScopeIpamArn() *string
	// Defines if the scope is the default scope or not.
	IpamScopeIsDefault() awscdk.IResolvable
	// The number of pools in a scope.
	IpamScopePoolCount() *float64
	// The type of the scope.
	IpamScopeType() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The underlying IPAM scope CloudFormation resource.
	// See: [AWS::EC2::IPAMScope](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html)
	//
	Resource() awsec2.CfnIPAMScope
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	AddPool() IIpamPool
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for PrivateIpamScope
type jsiiProxy_PrivateIpamScope struct {
	internal.Type__awscdkResource
	jsiiProxy_IPrivateIpamScope
}

func (j *jsiiProxy_PrivateIpamScope) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) Ipam() IIpam {
	var returns IIpam
	_jsii_.Get(
		j,
		"ipam",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) IpamScopeArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) IpamScopeId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) IpamScopeIpamArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeIpamArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) IpamScopeIsDefault() awscdk.IResolvable {
	var returns awscdk.IResolvable
	_jsii_.Get(
		j,
		"ipamScopeIsDefault",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) IpamScopePoolCount() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"ipamScopePoolCount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) IpamScopeType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ipamScopeType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) Resource() awsec2.CfnIPAMScope {
	var returns awsec2.CfnIPAMScope
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_PrivateIpamScope) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewPrivateIpamScope(scope constructs.IConstruct, id *string, props *PrivateIpamScopeProps) PrivateIpamScope {
	_init_.Initialize()

	if err := validateNewPrivateIpamScopeParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_PrivateIpamScope{}

	_jsii_.Create(
		"cdk-extensions.ec2.PrivateIpamScope",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewPrivateIpamScope_Override(p PrivateIpamScope, scope constructs.IConstruct, id *string, props *PrivateIpamScopeProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2.PrivateIpamScope",
		[]interface{}{scope, id, props},
		p,
	)
}

// Imports an existing IPAM scope by specifying its Amazon Resource Name (ARN).
//
// Returns: An object representing the imported IPAM scope.
func PrivateIpamScope_FromIpamScopeArn(scope constructs.IConstruct, id *string, ipamScopeArn *string) IPrivateIpamScope {
	_init_.Initialize()

	if err := validatePrivateIpamScope_FromIpamScopeArnParameters(scope, id, ipamScopeArn); err != nil {
		panic(err)
	}
	var returns IPrivateIpamScope

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.PrivateIpamScope",
		"fromIpamScopeArn",
		[]interface{}{scope, id, ipamScopeArn},
		&returns,
	)

	return returns
}

// Imports an existing IAPM scope by explicitly specifying its attributes.
//
// Returns: An object representing the imported IPAM scope.
func PrivateIpamScope_FromIpamScopeAttributes(scope constructs.IConstruct, id *string, attrs *IpamScopeAttributes) IPrivateIpamScope {
	_init_.Initialize()

	if err := validatePrivateIpamScope_FromIpamScopeAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IPrivateIpamScope

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.PrivateIpamScope",
		"fromIpamScopeAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Imports an existing IPAM scope by explicitly specifying its AWS generated ID.
//
// Returns: An object representing the imported IPAM scope.
func PrivateIpamScope_FromIpamScopeId(scope constructs.IConstruct, id *string, ipamScopeId *string) IPrivateIpamScope {
	_init_.Initialize()

	if err := validatePrivateIpamScope_FromIpamScopeIdParameters(scope, id, ipamScopeId); err != nil {
		panic(err)
	}
	var returns IPrivateIpamScope

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.PrivateIpamScope",
		"fromIpamScopeId",
		[]interface{}{scope, id, ipamScopeId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func PrivateIpamScope_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validatePrivateIpamScope_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.PrivateIpamScope",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func PrivateIpamScope_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePrivateIpamScope_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.PrivateIpamScope",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func PrivateIpamScope_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validatePrivateIpamScope_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.PrivateIpamScope",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func PrivateIpamScope_ARN_FORMAT() awscdk.ArnFormat {
	_init_.Initialize()
	var returns awscdk.ArnFormat
	_jsii_.StaticGet(
		"cdk-extensions.ec2.PrivateIpamScope",
		"ARN_FORMAT",
		&returns,
	)
	return returns
}

func (p *jsiiProxy_PrivateIpamScope) AddPool() IIpamPool {
	var returns IIpamPool

	_jsii_.Invoke(
		p,
		"addPool",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PrivateIpamScope) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := p.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		p,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (p *jsiiProxy_PrivateIpamScope) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PrivateIpamScope) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := p.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PrivateIpamScope) GetResourceNameAttribute(nameAttr *string) *string {
	if err := p.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		p,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (p *jsiiProxy_PrivateIpamScope) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		p,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

