package ec2

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2/internal"
)

// Creates a route table for traffic being processed by a transit gateway.
//
// When traffic is routed to a transit gateway via an attachment, the route
// table associated with that attachment is used when evaluating how the
// inbound traffic should be routed.
// See: [AWS::EC2::TransitGatewayRouteTable](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayroutetable.html)
//
type TransitGatewayRouteTable interface {
	awscdk.Resource
	ITransitGatewayRouteTable
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The name of the transit gateway route table.
	//
	// Used to tag the route table with a name that will be displayed in the AWS
	// EC2 console.
	// See: [TransitGatewayRouteTable Tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayroutetable.html#cfn-ec2-transitgatewayroutetable-tags)
	//
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The underlying TransitGatewayRouteTable CloudFormation resource.
	// See: [AWS::EC2::TransitGatewayRouteTable](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayroutetable.html)
	//
	Resource() awsec2.CfnTransitGatewayRouteTable
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The transit gateway for which the route table should be created.
	// See: [TransitGatewayRouteTable TransitGatewayId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayroutetable.html#cfn-ec2-transitgatewayroutetable-transitgatewayid)
	//
	TransitGateway() ITransitGateway
	// The ARN of this transit gateway route table.
	TransitGatewayRouteTableArn() *string
	// The ID of this transit gateway route table.
	TransitGatewayRouteTableId() *string
	// Adds a route to this transit gateway route table.
	//
	// Returns: The TransitGatewayRoute that was added.
	AddRoute(options *TransitGatewayRouteOptions) TransitGatewayRoute
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for TransitGatewayRouteTable
type jsiiProxy_TransitGatewayRouteTable struct {
	internal.Type__awscdkResource
	jsiiProxy_ITransitGatewayRouteTable
}

func (j *jsiiProxy_TransitGatewayRouteTable) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) Resource() awsec2.CfnTransitGatewayRouteTable {
	var returns awsec2.CfnTransitGatewayRouteTable
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) TransitGateway() ITransitGateway {
	var returns ITransitGateway
	_jsii_.Get(
		j,
		"transitGateway",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) TransitGatewayRouteTableArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"transitGatewayRouteTableArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TransitGatewayRouteTable) TransitGatewayRouteTableId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"transitGatewayRouteTableId",
		&returns,
	)
	return returns
}


// Creates a new instance of the TransitGatewayRouteTable class.
func NewTransitGatewayRouteTable(scope constructs.Construct, id *string, props *TransitGatewayRouteTableProps) TransitGatewayRouteTable {
	_init_.Initialize()

	if err := validateNewTransitGatewayRouteTableParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_TransitGatewayRouteTable{}

	_jsii_.Create(
		"cdk-extensions.ec2.TransitGatewayRouteTable",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the TransitGatewayRouteTable class.
func NewTransitGatewayRouteTable_Override(t TransitGatewayRouteTable, scope constructs.Construct, id *string, props *TransitGatewayRouteTableProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2.TransitGatewayRouteTable",
		[]interface{}{scope, id, props},
		t,
	)
}

// Imports an existing transit gateway route table using its route table ID.
//
// Returns: An object representing the imported transit gateway route table.
func TransitGatewayRouteTable_FromTransitGatewayRouteTableId(scope constructs.IConstruct, id *string, transitGatewayRouteTableId *string) ITransitGatewayRouteTable {
	_init_.Initialize()

	if err := validateTransitGatewayRouteTable_FromTransitGatewayRouteTableIdParameters(scope, id, transitGatewayRouteTableId); err != nil {
		panic(err)
	}
	var returns ITransitGatewayRouteTable

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.TransitGatewayRouteTable",
		"fromTransitGatewayRouteTableId",
		[]interface{}{scope, id, transitGatewayRouteTableId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func TransitGatewayRouteTable_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateTransitGatewayRouteTable_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.TransitGatewayRouteTable",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func TransitGatewayRouteTable_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateTransitGatewayRouteTable_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.TransitGatewayRouteTable",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func TransitGatewayRouteTable_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateTransitGatewayRouteTable_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.TransitGatewayRouteTable",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TransitGatewayRouteTable) AddRoute(options *TransitGatewayRouteOptions) TransitGatewayRoute {
	if err := t.validateAddRouteParameters(options); err != nil {
		panic(err)
	}
	var returns TransitGatewayRoute

	_jsii_.Invoke(
		t,
		"addRoute",
		[]interface{}{options},
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TransitGatewayRouteTable) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := t.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (t *jsiiProxy_TransitGatewayRouteTable) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		t,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TransitGatewayRouteTable) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := t.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		t,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TransitGatewayRouteTable) GetResourceNameAttribute(nameAttr *string) *string {
	if err := t.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		t,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TransitGatewayRouteTable) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		t,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

