package ec2

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2/internal"
)

type VpcCidrBlock interface {
	awscdk.Resource
	IVpcCidrBlock
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	Resource() awsec2.CfnVPCCidrBlock
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	Vpc() awsec2.IVpc
	VpcCidrBlockAddressFamily() *string
	VpcCidrBlockAssociationId() *string
	VpcCidrBlockCidr() *string
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for VpcCidrBlock
type jsiiProxy_VpcCidrBlock struct {
	internal.Type__awscdkResource
	jsiiProxy_IVpcCidrBlock
}

func (j *jsiiProxy_VpcCidrBlock) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) Resource() awsec2.CfnVPCCidrBlock {
	var returns awsec2.CfnVPCCidrBlock
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) Vpc() awsec2.IVpc {
	var returns awsec2.IVpc
	_jsii_.Get(
		j,
		"vpc",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) VpcCidrBlockAddressFamily() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vpcCidrBlockAddressFamily",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) VpcCidrBlockAssociationId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vpcCidrBlockAssociationId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcCidrBlock) VpcCidrBlockCidr() *string {
	var returns *string
	_jsii_.Get(
		j,
		"vpcCidrBlockCidr",
		&returns,
	)
	return returns
}


func NewVpcCidrBlock(scope constructs.IConstruct, id *string, props *VpcCidrBlockProps) VpcCidrBlock {
	_init_.Initialize()

	if err := validateNewVpcCidrBlockParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_VpcCidrBlock{}

	_jsii_.Create(
		"cdk-extensions.ec2.VpcCidrBlock",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewVpcCidrBlock_Override(v VpcCidrBlock, scope constructs.IConstruct, id *string, props *VpcCidrBlockProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2.VpcCidrBlock",
		[]interface{}{scope, id, props},
		v,
	)
}

func VpcCidrBlock_FromVpcCidrBlockAttributes(scope constructs.IConstruct, id *string, attrs *VpcCidrBlockAttributes) IVpcCidrBlock {
	_init_.Initialize()

	if err := validateVpcCidrBlock_FromVpcCidrBlockAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IVpcCidrBlock

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.VpcCidrBlock",
		"fromVpcCidrBlockAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func VpcCidrBlock_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVpcCidrBlock_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.VpcCidrBlock",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func VpcCidrBlock_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVpcCidrBlock_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.VpcCidrBlock",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func VpcCidrBlock_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVpcCidrBlock_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2.VpcCidrBlock",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcCidrBlock) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := v.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (v *jsiiProxy_VpcCidrBlock) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcCidrBlock) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := v.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcCidrBlock) GetResourceNameAttribute(nameAttr *string) *string {
	if err := v.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcCidrBlock) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

