package ram


// Configuration for importing an existing RAM resource share.
type ResourceShareAttributes struct {
	// The Amazon Resource Name (ARN) of the RAM resource share.
	ResourceShareArn *string `field:"optional" json:"resourceShareArn" yaml:"resourceShareArn"`
	// The ID generated by AWS for the RAM resource share.
	ResourceShareId *string `field:"optional" json:"resourceShareId" yaml:"resourceShareId"`
}

