package configrules

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsconfig"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsevents"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/config"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/configrules/internal"
)

type VpcDefaultSecurityGroupClosed interface {
	awsconfig.ManagedRule
	// The arn of the rule.
	ConfigRuleArn() *string
	// The compliance status of the rule.
	ConfigRuleComplianceType() *string
	// The id of the rule.
	ConfigRuleId() *string
	// The name of the rule.
	ConfigRuleName() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	IsCustomWithChanges() *bool
	SetIsCustomWithChanges(val *bool)
	IsManaged() *bool
	SetIsManaged(val *bool)
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	RemediationConfiguration() config.RemediationConfiguration
	RemediationPolicy() awsiam.ManagedPolicy
	RemediationRole() awsiam.Role
	RuleScope() awsconfig.RuleScope
	SetRuleScope(val awsconfig.RuleScope)
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Defines an EventBridge event rule which triggers for rule compliance events.
	OnComplianceChange(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Defines an EventBridge event rule which triggers for rule events.
	//
	// Use
	// `rule.addEventPattern(pattern)` to specify a filter.
	OnEvent(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Defines an EventBridge event rule which triggers for rule re-evaluation status events.
	OnReEvaluationStatus(id *string, options *awsevents.OnEventOptions) awsevents.Rule
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for VpcDefaultSecurityGroupClosed
type jsiiProxy_VpcDefaultSecurityGroupClosed struct {
	internal.Type__awsconfigManagedRule
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) ConfigRuleArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"configRuleArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) ConfigRuleComplianceType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"configRuleComplianceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) ConfigRuleId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"configRuleId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) ConfigRuleName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"configRuleName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) IsCustomWithChanges() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"isCustomWithChanges",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) IsManaged() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"isManaged",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) RemediationConfiguration() config.RemediationConfiguration {
	var returns config.RemediationConfiguration
	_jsii_.Get(
		j,
		"remediationConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) RemediationPolicy() awsiam.ManagedPolicy {
	var returns awsiam.ManagedPolicy
	_jsii_.Get(
		j,
		"remediationPolicy",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) RemediationRole() awsiam.Role {
	var returns awsiam.Role
	_jsii_.Get(
		j,
		"remediationRole",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) RuleScope() awsconfig.RuleScope {
	var returns awsconfig.RuleScope
	_jsii_.Get(
		j,
		"ruleScope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewVpcDefaultSecurityGroupClosed(scope constructs.IConstruct, id *string, props *VpcDefaultSecurityGroupClosedProps) VpcDefaultSecurityGroupClosed {
	_init_.Initialize()

	if err := validateNewVpcDefaultSecurityGroupClosedParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_VpcDefaultSecurityGroupClosed{}

	_jsii_.Create(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewVpcDefaultSecurityGroupClosed_Override(v VpcDefaultSecurityGroupClosed, scope constructs.IConstruct, id *string, props *VpcDefaultSecurityGroupClosedProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		[]interface{}{scope, id, props},
		v,
	)
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed)SetIsCustomWithChanges(val *bool) {
	_jsii_.Set(
		j,
		"isCustomWithChanges",
		val,
	)
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed)SetIsManaged(val *bool) {
	_jsii_.Set(
		j,
		"isManaged",
		val,
	)
}

func (j *jsiiProxy_VpcDefaultSecurityGroupClosed)SetRuleScope(val awsconfig.RuleScope) {
	_jsii_.Set(
		j,
		"ruleScope",
		val,
	)
}

// Imports an existing rule.
func VpcDefaultSecurityGroupClosed_FromConfigRuleName(scope constructs.Construct, id *string, configRuleName *string) awsconfig.IRule {
	_init_.Initialize()

	if err := validateVpcDefaultSecurityGroupClosed_FromConfigRuleNameParameters(scope, id, configRuleName); err != nil {
		panic(err)
	}
	var returns awsconfig.IRule

	_jsii_.StaticInvoke(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"fromConfigRuleName",
		[]interface{}{scope, id, configRuleName},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func VpcDefaultSecurityGroupClosed_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateVpcDefaultSecurityGroupClosed_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func VpcDefaultSecurityGroupClosed_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVpcDefaultSecurityGroupClosed_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func VpcDefaultSecurityGroupClosed_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateVpcDefaultSecurityGroupClosed_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func VpcDefaultSecurityGroupClosed_DEFAULT_DESCRIPTION() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"DEFAULT_DESCRIPTION",
		&returns,
	)
	return returns
}

func VpcDefaultSecurityGroupClosed_MANAGED_RULE_NAME() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"MANAGED_RULE_NAME",
		&returns,
	)
	return returns
}

func VpcDefaultSecurityGroupClosed_REMEDIATION_DOCUMENT_NAME() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.config_rules.VpcDefaultSecurityGroupClosed",
		"REMEDIATION_DOCUMENT_NAME",
		&returns,
	)
	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := v.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		v,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := v.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) GetResourceNameAttribute(nameAttr *string) *string {
	if err := v.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		v,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) OnComplianceChange(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := v.validateOnComplianceChangeParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		v,
		"onComplianceChange",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) OnEvent(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := v.validateOnEventParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		v,
		"onEvent",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) OnReEvaluationStatus(id *string, options *awsevents.OnEventOptions) awsevents.Rule {
	if err := v.validateOnReEvaluationStatusParameters(id, options); err != nil {
		panic(err)
	}
	var returns awsevents.Rule

	_jsii_.Invoke(
		v,
		"onReEvaluationStatus",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (v *jsiiProxy_VpcDefaultSecurityGroupClosed) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		v,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

