package lambda

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsevents"
	"github.com/aws/aws-cdk-go/awscdk/v2/awslogs"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsstepfunctions"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/lambda/internal"
)

// Deploys a solution that automatically sets a log retention policy for all CloudWatch log groups created by AWS Lamba.
//
// The controller consists of an EventBridge rule that detects the creation of
// new log groups and a state machine that sets a retention policy for any log
// groups that triggered the rule.
//
// The rule triggers for any log group that is created with a name that starts
// with `/aws/lambda/`.
//
// Currently existing log groups created by AWS Lambda are not affected by the
// policy. It is also possible that log groups created by means other than AWS
// Lambda that have a retention policy specified could have their retention
// policy overridden if the log group name starts with `/aws/lambda/`.
// See: [Reduce log-storage costs by automating retention settings in Amazon CloudWatch](https://aws.amazon.com/blogs/infrastructure-and-automation/reduce-log-storage-costs-by-automating-retention-settings-in-amazon-cloudwatch/)
//
type LogRetentionController interface {
	awscdk.Resource
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// Execution logging configuration for the state machine that is used to configure log retention for log groups created via AWS Lambda.
	// See: [StateMachine LoggingConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-loggingconfiguration)
	//
	ExecutionLogging() *ExecutionLogOptions
	// The log group which will receive execution events from the state machine.
	ExecutionLogGroup() awslogs.ILogGroup
	// The EventBridge rule that detects the creation of new log groups with a name matching the prefix used by AWS Lambda.
	LogGroupCreatedRule() awsevents.Rule
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The length of time logs sent to log groups created by AWS Lambda should be retained before being deleted.
	// See: [LogGroup RetentionInDays](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-retentionindays)
	//
	Retention() awslogs.RetentionDays
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The state machine that is triggered to add a retention policy for all new log groups that trigger the EventBridge rule.
	StateMachine() awsstepfunctions.StateMachine
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for LogRetentionController
type jsiiProxy_LogRetentionController struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_LogRetentionController) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) ExecutionLogging() *ExecutionLogOptions {
	var returns *ExecutionLogOptions
	_jsii_.Get(
		j,
		"executionLogging",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) ExecutionLogGroup() awslogs.ILogGroup {
	var returns awslogs.ILogGroup
	_jsii_.Get(
		j,
		"executionLogGroup",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) LogGroupCreatedRule() awsevents.Rule {
	var returns awsevents.Rule
	_jsii_.Get(
		j,
		"logGroupCreatedRule",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) Retention() awslogs.RetentionDays {
	var returns awslogs.RetentionDays
	_jsii_.Get(
		j,
		"retention",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_LogRetentionController) StateMachine() awsstepfunctions.StateMachine {
	var returns awsstepfunctions.StateMachine
	_jsii_.Get(
		j,
		"stateMachine",
		&returns,
	)
	return returns
}


// Creates a new instance of the LogRetentionController class.
func NewLogRetentionController(scope constructs.IConstruct, id *string, props *LogRetentionControllerProps) LogRetentionController {
	_init_.Initialize()

	if err := validateNewLogRetentionControllerParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_LogRetentionController{}

	_jsii_.Create(
		"cdk-extensions.lambda.LogRetentionController",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the LogRetentionController class.
func NewLogRetentionController_Override(l LogRetentionController, scope constructs.IConstruct, id *string, props *LogRetentionControllerProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.lambda.LogRetentionController",
		[]interface{}{scope, id, props},
		l,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func LogRetentionController_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateLogRetentionController_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.lambda.LogRetentionController",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func LogRetentionController_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateLogRetentionController_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.lambda.LogRetentionController",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func LogRetentionController_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateLogRetentionController_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.lambda.LogRetentionController",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (l *jsiiProxy_LogRetentionController) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := l.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		l,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (l *jsiiProxy_LogRetentionController) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		l,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (l *jsiiProxy_LogRetentionController) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := l.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		l,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (l *jsiiProxy_LogRetentionController) GetResourceNameAttribute(nameAttr *string) *string {
	if err := l.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		l,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (l *jsiiProxy_LogRetentionController) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		l,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

