package ec2patterns

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ec2patterns/internal"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ram"
)

type IpAddressManager interface {
	awscdk.Resource
	AllowExternalPricipals() *bool
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	Ipam() ec2.Ipam
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	ResourceShare() ram.ResourceShare
	SharingEnabled() *bool
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	AddPrivatePool(name *string, options *AddPoolOptions) ec2.IIpamPool
	AddRegion(region *string)
	AddStagePool(scope constructs.IConstruct, parent ec2.IIpamPool) ec2.IpamPool
	AllocatePrivateNetwork(scope constructs.IConstruct, id *string, options *AllocatePrivateNetworkOptions) ec2.IpamPool
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	RegisterAccount(account *string, pool ec2.IIpamPool)
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for IpAddressManager
type jsiiProxy_IpAddressManager struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_IpAddressManager) AllowExternalPricipals() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"allowExternalPricipals",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) Ipam() ec2.Ipam {
	var returns ec2.Ipam
	_jsii_.Get(
		j,
		"ipam",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) ResourceShare() ram.ResourceShare {
	var returns ram.ResourceShare
	_jsii_.Get(
		j,
		"resourceShare",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) SharingEnabled() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"sharingEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IpAddressManager) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewIpAddressManager(scope constructs.IConstruct, id *string, props *IpAddressManagerProps) IpAddressManager {
	_init_.Initialize()

	if err := validateNewIpAddressManagerParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_IpAddressManager{}

	_jsii_.Create(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewIpAddressManager_Override(i IpAddressManager, scope constructs.IConstruct, id *string, props *IpAddressManagerProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		[]interface{}{scope, id, props},
		i,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func IpAddressManager_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateIpAddressManager_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func IpAddressManager_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpAddressManager_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func IpAddressManager_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateIpAddressManager_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func IpAddressManager_DEFAULT_CIDR() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		"DEFAULT_CIDR",
		&returns,
	)
	return returns
}

func IpAddressManager_DEFAULT_POOL_ALLOCATION_MASK() *float64 {
	_init_.Initialize()
	var returns *float64
	_jsii_.StaticGet(
		"cdk-extensions.ec2_patterns.IpAddressManager",
		"DEFAULT_POOL_ALLOCATION_MASK",
		&returns,
	)
	return returns
}

func (i *jsiiProxy_IpAddressManager) AddPrivatePool(name *string, options *AddPoolOptions) ec2.IIpamPool {
	if err := i.validateAddPrivatePoolParameters(name, options); err != nil {
		panic(err)
	}
	var returns ec2.IIpamPool

	_jsii_.Invoke(
		i,
		"addPrivatePool",
		[]interface{}{name, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpAddressManager) AddRegion(region *string) {
	if err := i.validateAddRegionParameters(region); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"addRegion",
		[]interface{}{region},
	)
}

func (i *jsiiProxy_IpAddressManager) AddStagePool(scope constructs.IConstruct, parent ec2.IIpamPool) ec2.IpamPool {
	if err := i.validateAddStagePoolParameters(scope, parent); err != nil {
		panic(err)
	}
	var returns ec2.IpamPool

	_jsii_.Invoke(
		i,
		"addStagePool",
		[]interface{}{scope, parent},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpAddressManager) AllocatePrivateNetwork(scope constructs.IConstruct, id *string, options *AllocatePrivateNetworkOptions) ec2.IpamPool {
	if err := i.validateAllocatePrivateNetworkParameters(scope, id, options); err != nil {
		panic(err)
	}
	var returns ec2.IpamPool

	_jsii_.Invoke(
		i,
		"allocatePrivateNetwork",
		[]interface{}{scope, id, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpAddressManager) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_IpAddressManager) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpAddressManager) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpAddressManager) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_IpAddressManager) RegisterAccount(account *string, pool ec2.IIpamPool) {
	if err := i.validateRegisterAccountParameters(account, pool); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"registerAccount",
		[]interface{}{account, pool},
	)
}

func (i *jsiiProxy_IpAddressManager) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

