package aps

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

// Represents an APS workspace in AWS.
type IWorkspace interface {
	// The Amazon Resource Name (ARN) of the APS workspace.
	WorkspaceArn() *string
	// The ID generated by AWS for the APS workspace.
	WorkspaceId() *string
	// The Prometheus endpoint attribute of the workspace.
	//
	// This is the endpoint prefix without the remote_write or query API
	// appended.
	WorkspacePrometheusEndpoint() *string
}

// The jsii proxy for IWorkspace
type jsiiProxy_IWorkspace struct {
	_ byte // padding
}

func (j *jsiiProxy_IWorkspace) WorkspaceArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspaceArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IWorkspace) WorkspaceId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspaceId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IWorkspace) WorkspacePrometheusEndpoint() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspacePrometheusEndpoint",
		&returns,
	)
	return returns
}

