package sso

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awssso"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/sso/internal"
)

// Enables the attribute-based access control (ABAC) feature for the specified IAM Identity Center instance.
//
// You can also specify new attributes to add to
// your ABAC configuration during the enabling process. For more information
// about ABAC, see [Attribute-Based Access Control](https://docs.aws.amazon.com/singlesignon/latest/userguide/abac.html) in the IAM Identity Center
// User Guide.
type InstanceAccessControlAttributeConfiguration interface {
	awscdk.Resource
	// Lists the attributes that are configured for ABAC in the specified IAM Identity Center instance.
	//
	// This array is readonly. Changes made to the
	// array will not be reflected in this resource. To add new attributes use
	// the `{@link addAttribute}` method.
	Attributes() *[]AccessControlAttribute
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The ARN of the IAM Identity Center instance under which the operation will be executed.
	Instance() IInstance
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	PhysicalName() *string
	// The underlying InstanceAccessControlAttributeConfiguration CloudFormation resource.
	Resource() awssso.CfnInstanceAccessControlAttributeConfiguration
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Adds a new ABAC attribute in the specified IAM Identity Center instance.
	//
	// Returns: An AccessControlAttribute resource that will be applied to the
	// configuration and supports continued management.
	AddAttribute(key *string, sources ...*string) AccessControlAttribute
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for InstanceAccessControlAttributeConfiguration
type jsiiProxy_InstanceAccessControlAttributeConfiguration struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) Attributes() *[]AccessControlAttribute {
	var returns *[]AccessControlAttribute
	_jsii_.Get(
		j,
		"attributes",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) Instance() IInstance {
	var returns IInstance
	_jsii_.Get(
		j,
		"instance",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) Resource() awssso.CfnInstanceAccessControlAttributeConfiguration {
	var returns awssso.CfnInstanceAccessControlAttributeConfiguration
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InstanceAccessControlAttributeConfiguration) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Creates a new instance of the InstanceAccessControlAttributeConfiguration class.
func NewInstanceAccessControlAttributeConfiguration(scope constructs.Construct, id *string, props *InstanceAccessControlAttributeConfigurationProps) InstanceAccessControlAttributeConfiguration {
	_init_.Initialize()

	if err := validateNewInstanceAccessControlAttributeConfigurationParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_InstanceAccessControlAttributeConfiguration{}

	_jsii_.Create(
		"cdk-extensions.sso.InstanceAccessControlAttributeConfiguration",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the InstanceAccessControlAttributeConfiguration class.
func NewInstanceAccessControlAttributeConfiguration_Override(i InstanceAccessControlAttributeConfiguration, scope constructs.Construct, id *string, props *InstanceAccessControlAttributeConfigurationProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.sso.InstanceAccessControlAttributeConfiguration",
		[]interface{}{scope, id, props},
		i,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func InstanceAccessControlAttributeConfiguration_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateInstanceAccessControlAttributeConfiguration_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.sso.InstanceAccessControlAttributeConfiguration",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func InstanceAccessControlAttributeConfiguration_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateInstanceAccessControlAttributeConfiguration_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.sso.InstanceAccessControlAttributeConfiguration",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func InstanceAccessControlAttributeConfiguration_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateInstanceAccessControlAttributeConfiguration_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.sso.InstanceAccessControlAttributeConfiguration",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InstanceAccessControlAttributeConfiguration) AddAttribute(key *string, sources ...*string) AccessControlAttribute {
	if err := i.validateAddAttributeParameters(key); err != nil {
		panic(err)
	}
	args := []interface{}{key}
	for _, a := range sources {
		args = append(args, a)
	}

	var returns AccessControlAttribute

	_jsii_.Invoke(
		i,
		"addAttribute",
		args,
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InstanceAccessControlAttributeConfiguration) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_InstanceAccessControlAttributeConfiguration) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InstanceAccessControlAttributeConfiguration) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InstanceAccessControlAttributeConfiguration) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InstanceAccessControlAttributeConfiguration) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

