package networkmanager

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsnetworkmanager"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/networkmanager/internal"
)

type GlobalNetwork interface {
	awscdk.Resource
	IGlobalNetwork
	Description() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	GlobalNetworkArn() *string
	GlobalNetworkId() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	Resource() awsnetworkmanager.CfnGlobalNetwork
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	RegisterTransitGateway(id *string, options *RegisterTransitGatewayProps) ITransitGatewayRegistration
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for GlobalNetwork
type jsiiProxy_GlobalNetwork struct {
	internal.Type__awscdkResource
	jsiiProxy_IGlobalNetwork
}

func (j *jsiiProxy_GlobalNetwork) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) GlobalNetworkArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"globalNetworkArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) GlobalNetworkId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"globalNetworkId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) Resource() awsnetworkmanager.CfnGlobalNetwork {
	var returns awsnetworkmanager.CfnGlobalNetwork
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalNetwork) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewGlobalNetwork(scope constructs.IConstruct, id *string, props *GlobalNetworkProps) GlobalNetwork {
	_init_.Initialize()

	if err := validateNewGlobalNetworkParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_GlobalNetwork{}

	_jsii_.Create(
		"cdk-extensions.networkmanager.GlobalNetwork",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewGlobalNetwork_Override(g GlobalNetwork, scope constructs.IConstruct, id *string, props *GlobalNetworkProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.networkmanager.GlobalNetwork",
		[]interface{}{scope, id, props},
		g,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func GlobalNetwork_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateGlobalNetwork_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.networkmanager.GlobalNetwork",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func GlobalNetwork_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGlobalNetwork_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.networkmanager.GlobalNetwork",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func GlobalNetwork_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGlobalNetwork_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.networkmanager.GlobalNetwork",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalNetwork) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := g.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (g *jsiiProxy_GlobalNetwork) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalNetwork) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := g.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalNetwork) GetResourceNameAttribute(nameAttr *string) *string {
	if err := g.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalNetwork) RegisterTransitGateway(id *string, options *RegisterTransitGatewayProps) ITransitGatewayRegistration {
	if err := g.validateRegisterTransitGatewayParameters(id, options); err != nil {
		panic(err)
	}
	var returns ITransitGatewayRegistration

	_jsii_.Invoke(
		g,
		"registerTransitGateway",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalNetwork) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

