package config

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsconfig"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/config/internal"
)

type RemediationConfiguration interface {
	awscdk.Resource
	IRemediationConfiguration
	Automatic() *bool
	ConfigRule() awsconfig.IRule
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	MaximumAutomaticAttempts() *float64
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	RemediationConfigurationArn() *string
	RemediationConfigurationName() *string
	Resource() awsconfig.CfnRemediationConfiguration
	ResourceType() *string
	RetryInterval() awscdk.Duration
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	AddParameter(key *string, values ...*string)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	RenderParameters() interface{}
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for RemediationConfiguration
type jsiiProxy_RemediationConfiguration struct {
	internal.Type__awscdkResource
	jsiiProxy_IRemediationConfiguration
}

func (j *jsiiProxy_RemediationConfiguration) Automatic() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"automatic",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) ConfigRule() awsconfig.IRule {
	var returns awsconfig.IRule
	_jsii_.Get(
		j,
		"configRule",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) MaximumAutomaticAttempts() *float64 {
	var returns *float64
	_jsii_.Get(
		j,
		"maximumAutomaticAttempts",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) RemediationConfigurationArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"remediationConfigurationArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) RemediationConfigurationName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"remediationConfigurationName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) Resource() awsconfig.CfnRemediationConfiguration {
	var returns awsconfig.CfnRemediationConfiguration
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) ResourceType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"resourceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) RetryInterval() awscdk.Duration {
	var returns awscdk.Duration
	_jsii_.Get(
		j,
		"retryInterval",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RemediationConfiguration) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewRemediationConfiguration(scope constructs.IConstruct, id *string, props *RemediationConfigurationProps) RemediationConfiguration {
	_init_.Initialize()

	if err := validateNewRemediationConfigurationParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_RemediationConfiguration{}

	_jsii_.Create(
		"cdk-extensions.config.RemediationConfiguration",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewRemediationConfiguration_Override(r RemediationConfiguration, scope constructs.IConstruct, id *string, props *RemediationConfigurationProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.config.RemediationConfiguration",
		[]interface{}{scope, id, props},
		r,
	)
}

func RemediationConfiguration_FromRemediationConfigurationArn(scope constructs.IConstruct, id *string, arn *string) IRemediationConfiguration {
	_init_.Initialize()

	if err := validateRemediationConfiguration_FromRemediationConfigurationArnParameters(scope, id, arn); err != nil {
		panic(err)
	}
	var returns IRemediationConfiguration

	_jsii_.StaticInvoke(
		"cdk-extensions.config.RemediationConfiguration",
		"fromRemediationConfigurationArn",
		[]interface{}{scope, id, arn},
		&returns,
	)

	return returns
}

func RemediationConfiguration_FromRemediationConfigurationAttributes(scope constructs.IConstruct, id *string, attrs *RemediationConfigurationAttributes) IRemediationConfiguration {
	_init_.Initialize()

	if err := validateRemediationConfiguration_FromRemediationConfigurationAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IRemediationConfiguration

	_jsii_.StaticInvoke(
		"cdk-extensions.config.RemediationConfiguration",
		"fromRemediationConfigurationAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

func RemediationConfiguration_FromRemediationConfigurationName(scope constructs.IConstruct, id *string, name *string) IRemediationConfiguration {
	_init_.Initialize()

	if err := validateRemediationConfiguration_FromRemediationConfigurationNameParameters(scope, id, name); err != nil {
		panic(err)
	}
	var returns IRemediationConfiguration

	_jsii_.StaticInvoke(
		"cdk-extensions.config.RemediationConfiguration",
		"fromRemediationConfigurationName",
		[]interface{}{scope, id, name},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func RemediationConfiguration_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateRemediationConfiguration_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.config.RemediationConfiguration",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func RemediationConfiguration_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateRemediationConfiguration_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.config.RemediationConfiguration",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func RemediationConfiguration_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateRemediationConfiguration_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.config.RemediationConfiguration",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func RemediationConfiguration_ARN_FORMAT() awscdk.ArnFormat {
	_init_.Initialize()
	var returns awscdk.ArnFormat
	_jsii_.StaticGet(
		"cdk-extensions.config.RemediationConfiguration",
		"ARN_FORMAT",
		&returns,
	)
	return returns
}

func (r *jsiiProxy_RemediationConfiguration) AddParameter(key *string, values ...*string) {
	if err := r.validateAddParameterParameters(key); err != nil {
		panic(err)
	}
	args := []interface{}{key}
	for _, a := range values {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		r,
		"addParameter",
		args,
	)
}

func (r *jsiiProxy_RemediationConfiguration) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := r.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		r,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (r *jsiiProxy_RemediationConfiguration) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		r,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RemediationConfiguration) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := r.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		r,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RemediationConfiguration) GetResourceNameAttribute(nameAttr *string) *string {
	if err := r.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		r,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RemediationConfiguration) RenderParameters() interface{} {
	var returns interface{}

	_jsii_.Invoke(
		r,
		"renderParameters",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RemediationConfiguration) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		r,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

