package glue

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsevents"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsglue"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/glue/internal"
)

type Crawler interface {
	awscdk.Resource
	Configuration() *CrawlerConfiguration
	CrawlerArn() *string
	CrawlerName() *string
	Database() Database
	DeleteBehavior() DeleteBehavior
	Description() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	PhysicalName() *string
	RecrawlBehavior() RecrawlBehavior
	Resource() awsglue.CfnCrawler
	Role() awsiam.Role
	ScheduleExpression() awsevents.Schedule
	SecurityConfiguration() SecurityConfiguration
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	TablePrefix() *string
	UpdateBehavior() UpdateBehavior
	AddClassifier(classifier *string)
	AddTarget(target ICrawlerTarget)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Crawler
type jsiiProxy_Crawler struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_Crawler) Configuration() *CrawlerConfiguration {
	var returns *CrawlerConfiguration
	_jsii_.Get(
		j,
		"configuration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) CrawlerArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"crawlerArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) CrawlerName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"crawlerName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Database() Database {
	var returns Database
	_jsii_.Get(
		j,
		"database",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) DeleteBehavior() DeleteBehavior {
	var returns DeleteBehavior
	_jsii_.Get(
		j,
		"deleteBehavior",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) RecrawlBehavior() RecrawlBehavior {
	var returns RecrawlBehavior
	_jsii_.Get(
		j,
		"recrawlBehavior",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Resource() awsglue.CfnCrawler {
	var returns awsglue.CfnCrawler
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Role() awsiam.Role {
	var returns awsiam.Role
	_jsii_.Get(
		j,
		"role",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) ScheduleExpression() awsevents.Schedule {
	var returns awsevents.Schedule
	_jsii_.Get(
		j,
		"scheduleExpression",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) SecurityConfiguration() SecurityConfiguration {
	var returns SecurityConfiguration
	_jsii_.Get(
		j,
		"securityConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) TablePrefix() *string {
	var returns *string
	_jsii_.Get(
		j,
		"tablePrefix",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Crawler) UpdateBehavior() UpdateBehavior {
	var returns UpdateBehavior
	_jsii_.Get(
		j,
		"updateBehavior",
		&returns,
	)
	return returns
}


// Creates a new instance of the Crawler class.
func NewCrawler(scope constructs.Construct, id *string, props *CrawlerProps) Crawler {
	_init_.Initialize()

	if err := validateNewCrawlerParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Crawler{}

	_jsii_.Create(
		"cdk-extensions.glue.Crawler",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the Crawler class.
func NewCrawler_Override(c Crawler, scope constructs.Construct, id *string, props *CrawlerProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.glue.Crawler",
		[]interface{}{scope, id, props},
		c,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func Crawler_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateCrawler_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.glue.Crawler",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func Crawler_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateCrawler_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.glue.Crawler",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func Crawler_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateCrawler_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.glue.Crawler",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Crawler) AddClassifier(classifier *string) {
	if err := c.validateAddClassifierParameters(classifier); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		c,
		"addClassifier",
		[]interface{}{classifier},
	)
}

func (c *jsiiProxy_Crawler) AddTarget(target ICrawlerTarget) {
	if err := c.validateAddTargetParameters(target); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		c,
		"addTarget",
		[]interface{}{target},
	)
}

func (c *jsiiProxy_Crawler) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := c.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		c,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (c *jsiiProxy_Crawler) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		c,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Crawler) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := c.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		c,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Crawler) GetResourceNameAttribute(nameAttr *string) *string {
	if err := c.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		c,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (c *jsiiProxy_Crawler) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		c,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

