package ekspatterns

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awseks"
	"github.com/aws/aws-cdk-go/awscdk/v2/awssecretsmanager"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsssm"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/aps"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/ekspatterns/internal"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/k8saws"
	"github.com/vibe-io/cdk-extensions-go/cdkextensions/k8sfargate"
)

type AwsIntegratedFargateCluster interface {
	awscdk.Resource
	AdotCollector() k8saws.AdotCollector
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	ExternalSecrets() k8saws.ExternalSecretsOperator
	FargateLogger() k8saws.FargateLogger
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	PrometheusService() k8sfargate.Prometheus
	PrometheusWorkspace() aps.IWorkspace
	Resource() awseks.FargateCluster
	Route53Dns() k8saws.Route53Dns
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	RegisterSecretsManagerSecret(id *string, secret awssecretsmanager.ISecret, options *k8saws.NamespacedExternalSecretOptions) k8saws.ExternalSecret
	RegisterSsmParameterSecret(id *string, parameter awsssm.IParameter, options *k8saws.NamespacedExternalSecretOptions) k8saws.ExternalSecret
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for AwsIntegratedFargateCluster
type jsiiProxy_AwsIntegratedFargateCluster struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) AdotCollector() k8saws.AdotCollector {
	var returns k8saws.AdotCollector
	_jsii_.Get(
		j,
		"adotCollector",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) ExternalSecrets() k8saws.ExternalSecretsOperator {
	var returns k8saws.ExternalSecretsOperator
	_jsii_.Get(
		j,
		"externalSecrets",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) FargateLogger() k8saws.FargateLogger {
	var returns k8saws.FargateLogger
	_jsii_.Get(
		j,
		"fargateLogger",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) PrometheusService() k8sfargate.Prometheus {
	var returns k8sfargate.Prometheus
	_jsii_.Get(
		j,
		"prometheusService",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) PrometheusWorkspace() aps.IWorkspace {
	var returns aps.IWorkspace
	_jsii_.Get(
		j,
		"prometheusWorkspace",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) Resource() awseks.FargateCluster {
	var returns awseks.FargateCluster
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) Route53Dns() k8saws.Route53Dns {
	var returns k8saws.Route53Dns
	_jsii_.Get(
		j,
		"route53Dns",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AwsIntegratedFargateCluster) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


func NewAwsIntegratedFargateCluster(scope constructs.Construct, id *string, props *AwsIntegratedFargateClusterProps) AwsIntegratedFargateCluster {
	_init_.Initialize()

	if err := validateNewAwsIntegratedFargateClusterParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_AwsIntegratedFargateCluster{}

	_jsii_.Create(
		"cdk-extensions.eks_patterns.AwsIntegratedFargateCluster",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewAwsIntegratedFargateCluster_Override(a AwsIntegratedFargateCluster, scope constructs.Construct, id *string, props *AwsIntegratedFargateClusterProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.eks_patterns.AwsIntegratedFargateCluster",
		[]interface{}{scope, id, props},
		a,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func AwsIntegratedFargateCluster_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateAwsIntegratedFargateCluster_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.eks_patterns.AwsIntegratedFargateCluster",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func AwsIntegratedFargateCluster_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateAwsIntegratedFargateCluster_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.eks_patterns.AwsIntegratedFargateCluster",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func AwsIntegratedFargateCluster_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateAwsIntegratedFargateCluster_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.eks_patterns.AwsIntegratedFargateCluster",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := a.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := a.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) GetResourceNameAttribute(nameAttr *string) *string {
	if err := a.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) RegisterSecretsManagerSecret(id *string, secret awssecretsmanager.ISecret, options *k8saws.NamespacedExternalSecretOptions) k8saws.ExternalSecret {
	if err := a.validateRegisterSecretsManagerSecretParameters(id, secret, options); err != nil {
		panic(err)
	}
	var returns k8saws.ExternalSecret

	_jsii_.Invoke(
		a,
		"registerSecretsManagerSecret",
		[]interface{}{id, secret, options},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) RegisterSsmParameterSecret(id *string, parameter awsssm.IParameter, options *k8saws.NamespacedExternalSecretOptions) k8saws.ExternalSecret {
	if err := a.validateRegisterSsmParameterSecretParameters(id, parameter, options); err != nil {
		panic(err)
	}
	var returns k8saws.ExternalSecret

	_jsii_.Invoke(
		a,
		"registerSsmParameterSecret",
		[]interface{}{id, parameter, options},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AwsIntegratedFargateCluster) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

