package alerting

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsevents"
	"github.com/aws/aws-cdk-go/awscdk/v2/awssecretsmanager"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsstepfunctions"
	"github.com/aws/constructs-go/constructs/v10"
)

// A standardized implementation that allows Discord messages to be sent in response to events detected in AWS.
//
// Intended for use with the `IssueManager` state machine which allows
// arbitrary types of events to be processed into standard values and then
// output or one of more issue tracking services.
type Discord interface {
	IssuePluginBase
	IIssueHandler
	// Destination pointing to a Jira instance where tickets are to be created.
	ApiDestination() awsevents.ApiDestination
	// The default Discord channel where messages processed by the handler should be sent if no override is given.
	Channel() *string
	// API connection providing details of how to communicate with the configured Jira instance.
	Connection() awsevents.Connection
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The event bus to use to trigger writes to the Jira instance.
	//
	// This integration formats a Jira API response and then sends it to a Jira
	// instance by means of an EventBridge Destination API and a specially
	// crafted event pattern. This is the event bus where the rule to trigger the
	// API will be added and the trigger event will be sent.
	EventBus() awsevents.IEventBus
	// The State Machine that handles creating a Jira ticket for a passed issue.
	//
	// Internally this state machine uses the AWS managed `AWS-CreateJiraIssue`
	// SSM Automation document.
	Handler() awsstepfunctions.IStateMachine
	Logging() *StateMachineLogging
	// Collection of users or roles who should be mentioned by default when sending a message to Discord.
	Mentions() *[]*string
	// The human friendly name that can be used to identify the plugin.
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The length of time that the State Machine that handles creation of Jira tickets is allowed to run before timing out.
	Timeout() awscdk.Duration
	// The token for a Discord bot that has permissions to post in the destination channels.
	//
	// The secret should be in JSON format and contain the
	// key:
	//
	// token: The token for the bot that has permissions to post in the
	// destination Discord channels.
	Token() awssecretsmanager.ISecret
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	BuildEventOverrides(options *DiscordOverrideOptions) IssueHandlerOverride
	BuildLogging() *awsstepfunctions.LogOptions
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Discord
type jsiiProxy_Discord struct {
	jsiiProxy_IssuePluginBase
	jsiiProxy_IIssueHandler
}

func (j *jsiiProxy_Discord) ApiDestination() awsevents.ApiDestination {
	var returns awsevents.ApiDestination
	_jsii_.Get(
		j,
		"apiDestination",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Channel() *string {
	var returns *string
	_jsii_.Get(
		j,
		"channel",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Connection() awsevents.Connection {
	var returns awsevents.Connection
	_jsii_.Get(
		j,
		"connection",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) EventBus() awsevents.IEventBus {
	var returns awsevents.IEventBus
	_jsii_.Get(
		j,
		"eventBus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Handler() awsstepfunctions.IStateMachine {
	var returns awsstepfunctions.IStateMachine
	_jsii_.Get(
		j,
		"handler",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Logging() *StateMachineLogging {
	var returns *StateMachineLogging
	_jsii_.Get(
		j,
		"logging",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Mentions() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"mentions",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Timeout() awscdk.Duration {
	var returns awscdk.Duration
	_jsii_.Get(
		j,
		"timeout",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Discord) Token() awssecretsmanager.ISecret {
	var returns awssecretsmanager.ISecret
	_jsii_.Get(
		j,
		"token",
		&returns,
	)
	return returns
}


// Creates a new instance of the JiraTicket class.
func NewDiscord(scope constructs.IConstruct, id *string, props *DiscordProps) Discord {
	_init_.Initialize()

	if err := validateNewDiscordParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Discord{}

	_jsii_.Create(
		"cdk-extensions.alerting.Discord",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Creates a new instance of the JiraTicket class.
func NewDiscord_Override(d Discord, scope constructs.IConstruct, id *string, props *DiscordProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.alerting.Discord",
		[]interface{}{scope, id, props},
		d,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func Discord_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateDiscord_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.Discord",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func Discord_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateDiscord_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.Discord",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func Discord_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateDiscord_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.Discord",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func Discord_DEFAULT_NAME() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.alerting.Discord",
		"DEFAULT_NAME",
		&returns,
	)
	return returns
}

func Discord_MESSAGES_ENDPOINT() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.alerting.Discord",
		"MESSAGES_ENDPOINT",
		&returns,
	)
	return returns
}

func (d *jsiiProxy_Discord) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := d.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		d,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (d *jsiiProxy_Discord) BuildEventOverrides(options *DiscordOverrideOptions) IssueHandlerOverride {
	if err := d.validateBuildEventOverridesParameters(options); err != nil {
		panic(err)
	}
	var returns IssueHandlerOverride

	_jsii_.Invoke(
		d,
		"buildEventOverrides",
		[]interface{}{options},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Discord) BuildLogging() *awsstepfunctions.LogOptions {
	var returns *awsstepfunctions.LogOptions

	_jsii_.Invoke(
		d,
		"buildLogging",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Discord) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Discord) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := d.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		d,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Discord) GetResourceNameAttribute(nameAttr *string) *string {
	if err := d.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		d,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (d *jsiiProxy_Discord) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		d,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

