package alerting

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsstepfunctions"
	"github.com/aws/constructs-go/constructs/v10"
)

type GuardDutyFinding interface {
	IssueParserPluginBase
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	Handler() awsstepfunctions.IStateMachine
	Logging() *StateMachineLogging
	MatchType() *string
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	Timeout() awscdk.Duration
	Triggers() *[]IssueTrigger
	AddDefaultTrigger() IssueTrigger
	AddSectionField(id *string, key *string, path *string) awsstepfunctions.Chain
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	Bind(_scope constructs.IConstruct) *[]IssueTrigger
	BuildLogging() *awsstepfunctions.LogOptions
	BuildSeverityMap() awsstepfunctions.Chain
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	RegisterIssueTrigger(id *string, options *GuardDutyFindingRuleOptions) IssueTrigger
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for GuardDutyFinding
type jsiiProxy_GuardDutyFinding struct {
	jsiiProxy_IssueParserPluginBase
}

func (j *jsiiProxy_GuardDutyFinding) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Handler() awsstepfunctions.IStateMachine {
	var returns awsstepfunctions.IStateMachine
	_jsii_.Get(
		j,
		"handler",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Logging() *StateMachineLogging {
	var returns *StateMachineLogging
	_jsii_.Get(
		j,
		"logging",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) MatchType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"matchType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Timeout() awscdk.Duration {
	var returns awscdk.Duration
	_jsii_.Get(
		j,
		"timeout",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GuardDutyFinding) Triggers() *[]IssueTrigger {
	var returns *[]IssueTrigger
	_jsii_.Get(
		j,
		"triggers",
		&returns,
	)
	return returns
}


func NewGuardDutyFinding(scope constructs.IConstruct, id *string, props *GuardDutyFindingProps) GuardDutyFinding {
	_init_.Initialize()

	if err := validateNewGuardDutyFindingParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_GuardDutyFinding{}

	_jsii_.Create(
		"cdk-extensions.alerting.GuardDutyFinding",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewGuardDutyFinding_Override(g GuardDutyFinding, scope constructs.IConstruct, id *string, props *GuardDutyFindingProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.alerting.GuardDutyFinding",
		[]interface{}{scope, id, props},
		g,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func GuardDutyFinding_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateGuardDutyFinding_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.GuardDutyFinding",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func GuardDutyFinding_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGuardDutyFinding_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.GuardDutyFinding",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func GuardDutyFinding_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateGuardDutyFinding_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.GuardDutyFinding",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func GuardDutyFinding_MATCH_TYPE() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.alerting.GuardDutyFinding",
		"MATCH_TYPE",
		&returns,
	)
	return returns
}

func GuardDutyFinding_SEVERITIES() *[]GuardDutySeverity {
	_init_.Initialize()
	var returns *[]GuardDutySeverity
	_jsii_.StaticGet(
		"cdk-extensions.alerting.GuardDutyFinding",
		"SEVERITIES",
		&returns,
	)
	return returns
}

func (g *jsiiProxy_GuardDutyFinding) AddDefaultTrigger() IssueTrigger {
	var returns IssueTrigger

	_jsii_.Invoke(
		g,
		"addDefaultTrigger",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) AddSectionField(id *string, key *string, path *string) awsstepfunctions.Chain {
	if err := g.validateAddSectionFieldParameters(id, key, path); err != nil {
		panic(err)
	}
	var returns awsstepfunctions.Chain

	_jsii_.Invoke(
		g,
		"addSectionField",
		[]interface{}{id, key, path},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := g.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (g *jsiiProxy_GuardDutyFinding) Bind(_scope constructs.IConstruct) *[]IssueTrigger {
	if err := g.validateBindParameters(_scope); err != nil {
		panic(err)
	}
	var returns *[]IssueTrigger

	_jsii_.Invoke(
		g,
		"bind",
		[]interface{}{_scope},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) BuildLogging() *awsstepfunctions.LogOptions {
	var returns *awsstepfunctions.LogOptions

	_jsii_.Invoke(
		g,
		"buildLogging",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) BuildSeverityMap() awsstepfunctions.Chain {
	var returns awsstepfunctions.Chain

	_jsii_.Invoke(
		g,
		"buildSeverityMap",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := g.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) GetResourceNameAttribute(nameAttr *string) *string {
	if err := g.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		g,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) RegisterIssueTrigger(id *string, options *GuardDutyFindingRuleOptions) IssueTrigger {
	if err := g.validateRegisterIssueTriggerParameters(id, options); err != nil {
		panic(err)
	}
	var returns IssueTrigger

	_jsii_.Invoke(
		g,
		"registerIssueTrigger",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GuardDutyFinding) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

