package alerting

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/vibe-io/cdk-extensions-go/cdkextensions/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsstepfunctions"
	"github.com/aws/constructs-go/constructs/v10"
)

type InspectorFinding interface {
	IssueParserPluginBase
	IIssueParser
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	Handler() awsstepfunctions.IStateMachine
	Logging() *StateMachineLogging
	MatchType() *string
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	Timeout() awscdk.Duration
	Triggers() *[]IssueTrigger
	AddDefaultTrigger() IssueTrigger
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	Bind(_node constructs.IConstruct) *[]IssueTrigger
	BuildDescription() DescriptionBuilder
	BuildLogging() *awsstepfunctions.LogOptions
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	RegisterIssueTrigger(id *string, options *InspectorFindingEventOptions) IssueTrigger
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for InspectorFinding
type jsiiProxy_InspectorFinding struct {
	jsiiProxy_IssueParserPluginBase
	jsiiProxy_IIssueParser
}

func (j *jsiiProxy_InspectorFinding) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Handler() awsstepfunctions.IStateMachine {
	var returns awsstepfunctions.IStateMachine
	_jsii_.Get(
		j,
		"handler",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Logging() *StateMachineLogging {
	var returns *StateMachineLogging
	_jsii_.Get(
		j,
		"logging",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) MatchType() *string {
	var returns *string
	_jsii_.Get(
		j,
		"matchType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Timeout() awscdk.Duration {
	var returns awscdk.Duration
	_jsii_.Get(
		j,
		"timeout",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_InspectorFinding) Triggers() *[]IssueTrigger {
	var returns *[]IssueTrigger
	_jsii_.Get(
		j,
		"triggers",
		&returns,
	)
	return returns
}


func NewInspectorFinding(scope constructs.IConstruct, id *string, props *InspectorFindingProps) InspectorFinding {
	_init_.Initialize()

	if err := validateNewInspectorFindingParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_InspectorFinding{}

	_jsii_.Create(
		"cdk-extensions.alerting.InspectorFinding",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewInspectorFinding_Override(i InspectorFinding, scope constructs.IConstruct, id *string, props *InspectorFindingProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-extensions.alerting.InspectorFinding",
		[]interface{}{scope, id, props},
		i,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func InspectorFinding_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateInspectorFinding_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.InspectorFinding",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func InspectorFinding_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateInspectorFinding_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.InspectorFinding",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func InspectorFinding_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateInspectorFinding_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-extensions.alerting.InspectorFinding",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func InspectorFinding_MATCH_TYPE() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"cdk-extensions.alerting.InspectorFinding",
		"MATCH_TYPE",
		&returns,
	)
	return returns
}

func InspectorFinding_SEVERITIES() *[]InspectorSeverity {
	_init_.Initialize()
	var returns *[]InspectorSeverity
	_jsii_.StaticGet(
		"cdk-extensions.alerting.InspectorFinding",
		"SEVERITIES",
		&returns,
	)
	return returns
}

func (i *jsiiProxy_InspectorFinding) AddDefaultTrigger() IssueTrigger {
	var returns IssueTrigger

	_jsii_.Invoke(
		i,
		"addDefaultTrigger",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_InspectorFinding) Bind(_node constructs.IConstruct) *[]IssueTrigger {
	if err := i.validateBindParameters(_node); err != nil {
		panic(err)
	}
	var returns *[]IssueTrigger

	_jsii_.Invoke(
		i,
		"bind",
		[]interface{}{_node},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) BuildDescription() DescriptionBuilder {
	var returns DescriptionBuilder

	_jsii_.Invoke(
		i,
		"buildDescription",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) BuildLogging() *awsstepfunctions.LogOptions {
	var returns *awsstepfunctions.LogOptions

	_jsii_.Invoke(
		i,
		"buildLogging",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) RegisterIssueTrigger(id *string, options *InspectorFindingEventOptions) IssueTrigger {
	if err := i.validateRegisterIssueTriggerParameters(id, options); err != nil {
		panic(err)
	}
	var returns IssueTrigger

	_jsii_.Invoke(
		i,
		"registerIssueTrigger",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_InspectorFinding) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

